language ferrum/test/0.1

[ 

  [ ["name", "single"]
  , ["language", "ferrum/0.1"]
  -- , ["expect", "\"Apple\" ", "value", "\"Apple\""]
  -- , ["expect", "\"Apple\" ", "type", "{\"Apple\"}"]
  , ["expectValue", "\"Apple\" ", "\"Apple\""]
  , ["expectType", "\"Banana\" ", "{\"Banana\"}"]
  ]

, [ ["name", "plus"]
  , ["language", "ferrum/0.1"]
  , ["expectValue", "1 + 2", "3"]
  , ["expectType",  "2 + 3", "Int"]
  ]

, [ ["name", "str-add"]
  , ["language", "ferrum/0.1"]
  , ["project", "../fe/fe-in-fe/fe4-prelude.proj.fe"]
  , ["expectValue", "strAdd \"a\" \"b\" ", "\"ab\""]
  , ["expectType",  "strAdd \"a\" \"b\" ", "Str"]
  ]

,  [ ["name", "prelude"]
  , ["language", "ferrum/0.1"]
  , [ "type_check", "bidir" ]
  , ["project", "../fe/fe-in-fe/fe4-prelude.proj.fe"]
  , ["decls",
    """
       let x = 1;
       let y = 2;
       let z = 4;
       let a = x+(y+z);
       let b = a*7;
    """
    ]
  , ["expect", "b", "value", "49", "type", "Int"]
  ]

, [ ["name", "first"]
  , ["language", "ferrum/0.1"]
  , [ "type_check", "bidir" ]
  , ["project", "../fe/fe-in-fe/fe4-prelude.proj.fe"]
  , ["decls",
    """
       let x = 1;
       let y = 2;
       let z = 4;
       let a = x+(y+z);
       let b = a*7;
    """
    ]
  , ["expect", "b", "value", "49", "type", "Int"]
  , ["expect", "nilPos", "value", "[0,0,0]"]
  -- , ["expect", "nilLoc", "value", "[\"\",[[0,0,0],[0,0,0]]]"]
  , ["expect", "nilLoc", "value", "[\"\",[0,0,0],[0,0,0]]"]
  ]


, [ ["name", "foldSum"]
  , ["language", "ferrum/0.1"]
  , [ "type_check", "bidir" ]
  , ["project", "../fe/fe-in-fe/fe4-prelude.proj.fe"]
  , ["decls",
    """
       let sum2 = (nums: List Int) -> foldl ((a:Int)-> (b:Int)-> a+b) 0 nums;
       let nums = [1,2,3,4,5];
    """
    ]
  , ["expect", "sum2 nums", "value", "15", "type", "Int"]
  ]


, [ [ "name", "scanSimple" ]
  , [ "language", "ferrum/0.1" ]
  , [ "type_check", "bidir" ]
  -- , [ "type_check", "none" ]

  -- , [ "project", "../fe/fe4.proj.fe" ]
  , [ "project", "../fe/fe-in-fe/fe4-prelude.proj.fe" ]
  , [ "decls",
      """
       let toks = -> scanSimple "apple banana carrot";
       let toks2 = -> map ( ([tag, value, loc] : Token) -> value ) (toks[]);
      """
    ]
  , [ "expect", "toks2[]", "value",
      """
       ["apple","banana","carrot"]
      """
    ]
  ]


, [ [ "name", "scanWord" ]
  , [ "language", "ferrum/0.1" ]
  , [ "type_check", "bidir" ]

  -- , [ "project", "../fe/fe4.proj.fe" ]
  , [ "project", "../fe/fe-in-fe/fe4-prelude.proj.fe" ]
  , [ "decls",
      """
       let toks1 = -> scan "  apple ";
       let toks2 = -> scan 
              """  
                 apple
                  +
                   123
              """
              ;
       let toks3 = -> scan 
              """  
                 -- a comment
                  " a string\n "
                   123
              """
              ;
       
        let toks4 = -> scan
            """
             """
              abc
             """
               """
                  def
                   +
                    "ghi"
       
               """
       
            """
            ;

      """
    ]
  , [ "expect", "toks1[]", "value",
      """
       [["WORD","apple",["",[1,3,2],[1,8,7]]],["EOF","",["",[1,9,8],[1,9,8]]]]
      """
    ]
  , [ "expect", "toks2[]", "value",
      """
       [["WORD","apple",["",[1,3,2],[1,8,7]]],["OPER","+",["",[2,4,11],[2,5,12]]],["NUMBER",123,["",[3,5,17],[3,8,20]]],["EOF","",["",[3,8,20],[3,8,20]]]]
      """
    ]
  , [ "expect", "toks3[]", "value",
      """
       [["STRING"," a string\n ",["",[2,4,18],[2,18,32]]],["NUMBER",123,["",[3,5,37],[3,8,40]]],["EOF","",["",[3,8,40],[3,8,40]]]]
      """
    ]
  , [ "expect", "toks4[]", "value",
      """
       [["STRING","abc",["",[1,1,0],[3,4,12]]],["STRING","  def\n   +\n    \"ghi\"\n",["",[4,3,15],[9,6,55]]],["EOF","",["",[10,1,56],[10,1,56]]]]
      """
    ]
  ]


, [ [ "name", "scanHex" ]
  , [ "language", "ferrum/0.1" ]
  , [ "type_check", "bidir" ]

  -- , [ "project", "../fe/fe4.proj.fe" ]
  , [ "project", "../fe/fe-in-fe/fe4-prelude.proj.fe" ]
  , [ "decls",
      """
       -- let toks = -> scan "\"\\x41\"";
       let toks = -> scan 
          """
           "\x41\x70\x70\x6C\x65"
          """
          ;
       -- let toks = -> scan "\"\\t\" ";
       let toks2 = -> map (([tag, value, loc] : Token) -> value) (toks[]);
      """
    ]
  , [ "expect", "toks2[]", "value",
      """
       ["Apple",""]
      """
    ]
  ]

]

