-- language ferrum_test_0




[ 
  [ ['name', 'plus']
  , ['expr', "1+2"]
  , ['expected_value', "3"]
  ]

, [ ['name', 'let']
  , ['expr', "let {a=7;} in a"]
  , ['expected_value', "7"]
  ]

, [ ['name', 'lambda']
  , ['expr', "(\\a->a) 11"]
  , ['expected_value', "11"]
  ]

, [ ['name', 'fibs']
  , ['expr', 
      """
        let {f = fix \(f:(\int=> \int=> \int=> list int)) -> \(n:int)-> \(a:int)-> \(b:int)-> if n==0 then () else (a, f (n-1) b (a+b));} in f 10 1 1
      """
  ]
  , ['expected_value', "(1,1,2,3,5,8,13,21,34,55,())"]
  ]

, [ ['name', 'fibs_case']
  , ['expr', 
      """
        let {f = fix \(f:(\int=> \int=> \int=> list int)) -> \(n:int)-> \(a:int)-> \(b:int)-> case n of {0 -> (); _ -> (a, f (n-1) b (a+b));};} in f 10 1 1
      """
    ]
  , ['expected_value', "(1,1,2,3,5,8,13,21,34,55,())"]
  ]

, [ ['name', 'case_list']
  , ['expr', "case ([7,8,9]:list int) of { [a,b] -> a*b; [x,y,z] -> x+y+z; m -> m; }"]
  , ['expected_value', "24"]
  ]

, [ ['name', 'let_pat']
  , ['expr', "let { [a,b,c] = [4,5,6]; [x,y] = [7,8]; } in [a+b+c,x*y]"]
  , ['expected_value', "(15,56,())"]
  ]

, [ ['name', 'scan_isAlphanum']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "isAlphanum '3'"]
  , ['expected_value', "true"]
  -- , ('type_check', 'bidir')
  ]

, [ ['name', 'scan_isElem']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "isElem 'let' keywords"]
  , ['expected_value', "true"]
  ]

, [ ['name', 'loop_addup']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "addup 10"]
  , ['expected_value', "55"]
  ]

, [ ['name', 'scan_plus']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "lex (explode '12+34')"]
  , ['expected_value', '(((1,1),(1,2),"LexAtomic","AInt",12),((1,3),(1,3),"LexOp","+"),((1,4),(1,5),"LexAtomic","AInt",34),((1,6),(1,6),"LexEOF",()),())']
  ]

, [ ['name', 'scan_plus_whitespace']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "lex (explode ' 12  +  34  ')"]
  , ['expected_value', '(((1,2),(1,3),"LexAtomic","AInt",12),((1,6),(1,6),"LexOp","+"),((1,9),(1,10),"LexAtomic","AInt",34),((1,13),(1,13),"LexEOF",()),())']
  ]

, [ ['name', 'parse_num']
  , ['project', "../../fe/ferrum3.proj.fe"]
  -- , ['expr', "grammar_parse_expr (lex (explode '56'))"]
  , ['expr', "grammar_parse_expr (lex (explode '56'))"]
  , ['expected_value', '("ELit",56)']
  ]



, [ ['name', 'parse_add']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "grammar_parse_expr (lex (explode '56 + 78'))"]
  , ['expected_value', '("EApply",("EApply",("EVar","+"),"ELit",56),"ELit",78)']
  ]

, [ ['name', 'parse_lambda']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "grammar_parse_expr (lex (explode '\\\\a-> a'))"]
  , ['expected_value', '("ELambda",("EVar","a"),"EVar","a")']
  ]

, [ ['name', 'parse_fibs']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "grammar_parse_expr (lex (explode 'let {f = \\\\n-> \\\\a-> \\\\b-> if n==0 then () else (a, f (n-1) b (a+b));} in f 10 1 1'))"]
  , ['expected_value', '("ELet2",((("EVar","f"),"ELambda",("EVar","n"),"ELambda",("EVar","a"),"ELambda",("EVar","b"),"EApply",("EApply",("EApply",("EVar","if"),"EApply",("EApply",("EVar","=="),"EVar","n"),"ELit",0),"ELit",()),"EPair",("EVar","a"),"EApply",("EApply",("EApply",("EVar","f"),"EApply",("EApply",("EVar","-"),"EVar","n"),"ELit",1),"EVar","b"),"EApply",("EApply",("EVar","+"),"EVar","a"),"EVar","b"),()),"EApply",("EApply",("EApply",("EVar","f"),"ELit",10),"ELit",1),"ELit",1)']
  ]

, [ ['name', 'eval_one']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "eval_str_eager '1'"]
  , ['expected_value', '1']
  ]

, [ ['name', 'eval_add']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "eval_str_eager '1+2'"]
  , ['expected_value', '3']
  ]

, [ ['name', 'eval_non_rec']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "eval_str_eager 'let {a=126;} in a'"]
  , ['expected_value', '126']
  ]

, [ ['name', 'eval_call']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "eval_str_eager 'let { h = \\\\z-> z+z; g = \\\\x->h(x*x); f = \\\\y-> g (y+y); } in f 3'"]
  , ['expected_value', '72']
  ]

, [ ['name', 'eval_addup']
  , ['project', "../../fe/ferrum3.proj.fe"]
--  , ('expr', "eval2 (grammar_parse_expr (lex (explode 'let {f = \\\\n-> if n==0 then 0 else n + f (n-1);} in f 10'))) lazy_env")
  , ['expr', "eval_str_eager 'let {f = fix \\\\f-> \\\\n-> (if n==0 then (\\\\a->0) else (\\\\a->n + f (n-1)))();} in f 10'"]
  , ['expected_value', '55']
  ]

, [ ['name', 'eval_fibs_lazy']
  , ['project', "../../fe/ferrum3.proj.fe"]
--  , ('expr', "eval2 (grammar_parse_expr (lex (explode 'let {f = \\\\n-> \\\\a-> \\\\b-> if n==0 then () else (a, f (n-1) b (a+b));} in f 10 1 1'))) lazy_env")
  , ['expr', "eval_str_lazy 'let {f = \\\\n-> \\\\a-> \\\\b-> if n==0 then () else (a, f (n-1) b (a+b));} in f 10 1 1'"]
  , ['expected_value', '(1,1,2,3,5,8,13,21,34,55,())']
  ]

, [ ['name', 'eval_fibs_lazy-3']
  , ['project', "../../fe/ferrum3.proj.fe"]
--  , ('expr', "eval2 (grammar_parse_expr (lex (explode 'let {f = \\\\n-> \\\\a-> \\\\b-> if n==0 then () else (a, f (n-1) b (a+b));} in f 10 1 1'))) lazy_env")
  , ['expr', "eval_str_lazy 'let {f = \\\\n-> \\\\a-> \\\\b-> if n==0 then () else (a, f (n-1) b (a+b));} in f 10 1 1'"]
  , ['expected_value', '(1,1,2,3,5,8,13,21,34,55,())']
  ]

, [ ['name', 'eval_fibs_eager']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "eval_str_eager 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> (if n==0 then (\\\\_->()) else (\\\\_->(a, f (n-1) b (a+b))))();} in f 10 1 1'"]
  , ['expected_value', '(1,1,2,3,5,8,13,21,34,55,())']
  ]

, [ ['name', 'eval_fibs_eager-3']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "eval_str_eager 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> (if n==0 then (\\\\_->()) else (\\\\_->(a, f (n-1) b (a+b))))();} in f 10 1 1'"]
  , ['expected_value', '(1,1,2,3,5,8,13,21,34,55,())']
  ]

, [ ['name', 'parse_implode']
  , ['project', "../../fe/ferrum3.proj.fe"]
  -- , ['expr', "parse_decls_eof (lex (explode 'implode = \\\\strList-> foldl (\\\\a-> \\\\b-> a^b) (\"\") strList;'))"]
  , ['expr', "grammar_parse_top (lex (explode 'implode = \\\\strList-> foldl (\\\\a-> \\\\b-> a^b) (\"\") strList;'))"]
  , ['expected_value', '((("EVar","implode"),"ELambda",("EVar","strList"),"EApply",("EApply",("EApply",("EVar","foldl"),"ELambda",("EVar","a"),"ELambda",("EVar","b"),"EApply",("EApply",("EVar","^"),"EVar","a"),"EVar","b"),"ELit",""),"EVar","strList"),())']
  ]

, [ ['name', 'parse_prelude']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "grammar_parse_top (lex (explode fe2_prelude_text))"]
  ]

, [ ['name', 'parse_scanner']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "grammar_parse_top (lex (explode (fe2_scanner_text)))"]
  ]

, [ ['name', 'parse_parser']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "grammar_parse_top (lex (explode (fe2_parser_text)))"]
  ]

, [ ['name', 'parse_eval']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "grammar_parse_top (lex (explode (fe2_eval_text)))"]
  ]

]
