-- language ferrum_test_0

[
  [ ['name', 'one']
  , ['expr', 
      """
       1
      """
    ]
  ]

, [ ['name', 'rules']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "rules"]
  ]

, [ ['name', 'parse-ident']
  , ['project', "../../fe/ferrum3.proj.fe"]
  -- , ('expr', "parse_rule 'EXP' (lex (explode 'hello one'))")
  -- , ('expr', "test_parse2 'EXP' (lex (explode 'hello one'))")
  , ['expr', "test_parse_expr (lex (explode 'hello one'))"]
  , ['expected_value', '("Test PASSED","EApply",("EVar","hello"),"EVar","one")']
  ]

, [ ['name', 'parse-fibs']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', 
      """
          -- test_parse2 'EXP' (lex (explode 
          test_parse_expr (lex (explode 
          "let {f = fix \\(f:(\\int=> \\int=> \\int=> list int)) -> \\(n:int)-> \\(a:int)-> \\(b:int)-> if n==0 then () else (a, f (n-1) b (a+b));} in f 10 1 1"
          ))
      """
    ]
  , ['expected_value', '("Test PASSED","ELet2",((("EVar","f"),"EApply",("EVar","fix"),"ELambda",("EType",("EVar","f"),"TLambda",("EVar","int"),"TLambda",("EVar","int"),"TLambda",("EVar","int"),"EApply",("EVar","list"),"EVar","int"),"ELambda",("EType",("EVar","n"),"EVar","int"),"ELambda",("EType",("EVar","a"),"EVar","int"),"ELambda",("EType",("EVar","b"),"EVar","int"),"EApply",("EApply",("EApply",("EVar","if"),"EApply",("EApply",("EVar","=="),"EVar","n"),"ELit",0),"ELit",()),"EPair",("EVar","a"),"EApply",("EApply",("EApply",("EVar","f"),"EApply",("EApply",("EVar","-"),"EVar","n"),"ELit",1),"EVar","b"),"EApply",("EApply",("EVar","+"),"EVar","a"),"EVar","b"),()),"EApply",("EApply",("EApply",("EVar","f"),"ELit",10),"ELit",1),"ELit",1)']
  ]


, [ ['name', 'parse-lookup']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', 
      """  
          -- test_parse2 'TOP' (lex (explode 
          test_parse_top (lex (explode 
            'lookup = \\key-> \\(kvs: KVS@(list (pair any any))): tlT (hdT KVS) -> loop1 (\\(kvs:KVS)-> case kvs of { [] -> error ("lookup failed", key); ((k,v),kvs2) -> if key==k then break v else continue kvs2; } ) kvs;'
          ))
      """
    ]
  , ['expected_value', '"Test PASSED"']
  ]

, [ ['name', 'parse-prelude2']
  , ['project', "../../fe/ferrum3.proj.fe"]
  --, ('expr', "test_parse 'TOP' (lex (explode fe2_prelude_text))")
  , ['expr', "test_parse_top (lex (explode fe2_prelude_text))"]
  , ['expected_value', '"Test PASSED"']
  ]
, [ ['name', 'parse-scanner2']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe2_scanner_text))"]
  , ['expected_value', '"Test PASSED"']
  ]

, [ ['name', 'parse-parser2']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe2_parser_text))"]
  , ['expected_value', '"Test PASSED"']
  ]


, [ ['name', 'parse-eval2']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe2_eval_text))"]
  , ['expected_value', '"Test PASSED"']
  ]

, [ ['name', 'parse-prelude3']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe3_prelude_text))"]
  , ['expected_value', '"Test PASSED"']
  ]

, [ ['name', 'parse-scanner3']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe3_scanner_text))"]
  , ['expected_value', '"Test PASSED"']
  ]

, [ ['name', 'parse-parser3']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe3_parser_text))"]
  , ['expected_value', '"Test PASSED"']
  ]
  

, [ ['name', 'parse-grammar3']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe3_grammar_text))"]
  , ['expected_value', '"Test PASSED"']
  ]

, [ ['name', 'parse-eval3']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe3_eval_text))"]
  , ['expected_value', '"Test PASSED"']
  ]

, [ ['name', 'parse-codegen3']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode fe3_codegen_text))"]
  , ['expected_value', '"Test PASSED"']
  ]

, [ ['name', 'parse-project3']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_parse_top (lex (explode (concatStrs [fe3_prelude_text, fe3_scanner_text, fe3_parser_text, fe3_grammar_text, fe3_eval_text, fe3_codegen_text])))"]
  , ['expected_value', '"Test PASSED"']
  ]


-- , [ ('name', 'cg-project3')
--   , ('project', "../../fe/ferrum3.proj.fe")
--   , ('expr', "cg_expr_str (concatStrs ['let {', fe3_prelude_text, fe3_scanner_text, fe3_parser_text, fe3_grammar_text, fe3_eval_text, fe3_codegen_text, '} in 1'])))")
-- --  , ('expr', "cg_expr_str (concatStrs ['let {', 'a=1;b=2;c=3;', '} in a+b+c'])))")
-- --  , ('expr', "cg_expr_str (concatStrs ['let {', fe3_scanner_text, '} in a+b+c'])))")
-- --  , ('expr', "cg_expr_str (concatStrs ['let {', fe3_grammar_text, '} in 1'])))")
-- --  , ('expected_value', '1')
--   ]

, [ ['name', 'eval_fibs']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "eval_str_eager 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> (if (n == 0) then (\\\\_->()) else (\\\\_->(a, f (n - 1) b (a + b))))();} in f 10 1 1'"]
  , ['expr', "eval_str_eager_g 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> (if (n == 0) then (\\\\_->()) else (\\\\_->(a, f (n - 1) b (a + b))))();} in f 10 1 1'"]
  , ['expr', "eval_cg_expr_str 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> (if (n == 0) then (\\\\_->()) else (\\\\_->(a, f (n - 1) b (a + b))))();} in f 10 1 1'"]
  , ['expected_value', '(1,1,2,3,5,8,13,21,34,55,())']
  ]

, [ ['name', 'js_eval']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "jsEval '1+2'"]
  , ['expected_value', '3']
  ]

, [ ['name', 'cg_add']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "cg_expr_str '1+2'"]
  , ['expected_value', '"((_[\\"+\\"](1))(2))"']
  ]

, [ ['name', 'cg2_add']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "cg2_expr_str '1+2'"]
  , ['expected_value', '"(()=>{return (1+2)\\n})()"']
  ]

, [ ['name', 'cg_fibs']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "eval_cg_expr_str 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> (if (n == 0) then (\\\\_->()) else (\\\\_->(a, f (n - 1) b (a + b))))();} in f 10 1 1'"]
  , ['expr', "eval_cg_expr_str 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> (if (n == 0) then () else (a, f (n - 1) b (a + b)));} in f 10 1 1'"]
  , ['expr', "eval_cg_expr_str 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> case n of { 0-> (); _-> (a, f (n - 1) b (a + b));};} in f 10 1 1'"]
  , ['expr', "eval_cg2_expr_str 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> (if (n == 0) then () else (a, f (n - 1) b (a + b)));} in f 10 1 1'"]
  , ['expr', "eval_cg2_expr_str 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> case n of { 0-> (); _-> (a, f (n - 1) b (a + b));};} in f 10 1 1'"]
  , ['expr', "eval_cg_project 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> case n of { 0-> (); _-> (a, f (n - 1) b (a + b));};} in f 10 1 1'"]
  , ['expr', "eval_cg2_project 'let {f = fix \\\\f-> \\\\n-> \\\\a-> \\\\b-> case n of { 0-> (); _-> (a, f (n - 1) b (a + b));};} in f 10 1 1'"]

  , ['expected_value', '(1,1,2,3,5,8,13,21,34,55,())']
  ]

, [ ['name', 'io-hello']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "hello ()"]
  ]

, [ ['name', 'bootstrap']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "bootstrap ()"]
  ]

-- , [ ['name', 'copy-file']
--   , ['project', "../../fe/ferrum3.proj.fe"]
--   , ['expr', "test_copy_file ()"]
--   ]
-- 
-- , [ ['name', 'concat-files']
--   , ['project', "../../fe/ferrum3.proj.fe"]
--   , ['expr', "test_concat_files ()"]
--   ]

, [ ['name', 'load-project']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_load_project ()"]
  ]

, [ ['name', 'eval-project']
  , ['project', "../../fe/ferrum3.proj.fe"]
  , ['expr', "test_eval_project ()"]
  ]

-- , [ ('name', 'load-tests')
--   , ('project', "../../fe/ferrum3.proj.fe")
--   , ('expr', "test_ ()")
--   ]


]





